spring:
  application:
    name: InventoryBackend'

  datasource:
    url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update # Creates/updates tables automatically
      #ddl-auto: create-drop # Drops and rebuild the database schema on startup and shutdown (useful for testing)
    show-sql: true
    properties:
      hibernate:
        format_sql: true